// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class googleconstants
{
        public const string achievement_online_ponger = "CgkI78r8qZIMEAIQCA"; // <GPGSID>
        public const string event_total_games_played = "CgkI78r8qZIMEAIQDw"; // <GPGSID>
        public const string achievement_beat_the_ai = "CgkI78r8qZIMEAIQBg"; // <GPGSID>
        public const string event_local_multiplayer_games_played = "CgkI78r8qZIMEAIQDQ"; // <GPGSID>
        public const string leaderboard_most_points_scored__local_multiplayer = "CgkI78r8qZIMEAIQAg"; // <GPGSID>
        public const string leaderboard_biggest_point_difference__local_multiplayer = "CgkI78r8qZIMEAIQAw"; // <GPGSID>
        public const string achievement_online_victor = "CgkI78r8qZIMEAIQCg"; // <GPGSID>
        public const string leaderboard_games_played__all_game_modes = "CgkI78r8qZIMEAIQBA"; // <GPGSID>
        public const string event_single_player_games_won = "CgkI78r8qZIMEAIQDA"; // <GPGSID>
        public const string leaderboard_most_points_scored__single_player = "CgkI78r8qZIMEAIQAQ"; // <GPGSID>
        public const string achievement_local_mogul = "CgkI78r8qZIMEAIQCQ"; // <GPGSID>
        public const string event_online_multiplayer_games_won = "CgkI78r8qZIMEAIQDg"; // <GPGSID>
        public const string event_points_scored__local_multiplayer = "CgkI78r8qZIMEAIQEA"; // <GPGSID>
        public const string achievement_friendly_ponger = "CgkI78r8qZIMEAIQBw"; // <GPGSID>
        public const string achievement_you_love_this_game = "CgkI78r8qZIMEAIQCw"; // <GPGSID>
        public const string leaderboard_points_scored__local_multiplayer = "CgkI78r8qZIMEAIQBQ"; // <GPGSID>

}

